### ISSUE TITLE
Express에서 Jest suptertest 로 api테스트 할 때 class를 지원하지 않음

### ISSUE THREAD

**Issue by herrero-tranquilo** [herrero-tranquilo/RE#2]
Babel을 사용해야하나

**Comment by herrero-tranquilo** [comment]
```
    "@babel/cli": "^7.7.7",
    "@babel/core": "^7.7.7",
    "@babel/node": "^7.7.7",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/preset-env": "^7.7.7",

```
//.babelrc
```

{
  "presets": ["@babel/preset-env"],
  "plugins": ["@babel/plugin-proposal-class-properties"]
}

```
```
에러: 
 FAIL  src/__tests__/routes.test.js
  ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

      16 | });
      17 | 
    > 18 | router.get("/:id", async (req, res, next) => {
         | ^
      19 |   try {
      20 |     const exUser = await user.findOne({
      21 |       where: { id: req.params.id, deleteAt: null },

      at src/Routes/user.js:18:1
      at Object.<anonymous> (src/Routes/user.js:18:1)
      at Object.<anonymous> (src/Routes/index.js:2:14)
      at Object.<anonymous> (src/app.js:6:16)
      at Object.<anonymous> (src/__tests__/routes.test.js:2:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.37s
```

이런 에러가 뜬다

**Comment by herrero-tranquilo** [comment]
그냥 class =>function으로 바꿔도 해결 될 테지만 이왕 본김에 유지하고 바벨적용해서 start, dev, 빌드 스크립트까지 작성하자 다만 app.js 는 수정이 필요 할 듯 싶다.

express도 http로 한번 감싸기로 하자.

**Comment by herrero-tranquilo** [comment]
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at ClientHandshake.handshakeResult (node_modules/mysql2/lib/commands/client_handshake.js:145:26)
      at ClientHandshake.execute (node_modules/mysql2/lib/commands/command.js:39:22)
      at Connection.handlePacket (node_modules/mysql2/lib/connection.js:412:32)
      at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:70:12)
      at PacketParser.executeStart (node_modules/mysql2/lib/packet_parser.js:75:16)
(node:2292) UnhandledPromiseRejectionWarning: SequelizeConnectionError: authSwitch.authSwitchRequest is not a function
(node:2292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

sequelize.sync(); 때문

https://github.com/sequelize/sequelize/issues/7953
https://stackoverflow.com/questions/45113510/jest-cannot-handle-the-sequelize-sync-promise

**Comment by herrero-tranquilo** [comment]
해결 app.js 파일 밖으로 sequelize.sync()를 옮김
